#!/bin/bash
# shellcheck disable=SC1090

## Definitions

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
PLIST=${DIR}/plugins/plugin.list
ELIST=${DIR}/extensions/extension.list
DEV=true

## Colors

declare -A COLOR
COLOR=(
  [nc]='\033[0m'
  [erro]='\033[31m'
  [warn]='\033[33m'
  [done]='\033[32m'
  [info]='\033[34m'
)

## Output types

if ${DEV}; then
  function output () {
    declare input="${*:2}";
    echo -e "${COLOR[$1]}$(date +%F\ %T\ %z) | ${1} | ${input}${COLOR[nc]}"
  }
  function xt () {
    output "$1" "Set return code to $2"
    return "$2"
  }
else
  function output () {
    declare input=${*:2};
    echo -e "${COLOR[$1]}${input}${COLOR[nc]}"
  }
  function xt () {
    return "$2"
  }
fi

# Main run

function main () {
  export CWDIR=${DIR}/plugins/${1}
  if (containsElement "$1" "${plugins[@]}"); then
    if [ "$2" = "help" ]; then
      output "info" "$1"
    else
      source "${DIR}/plugins/${1}/main.sh"
    fi
  else
    output "erro" "Plugin $1 not found."
    avail-plugins
    output "info" "Tip: If you added the plugin recently, add it to the index with '${0##*/} index'"
  fi
}

function containsElement () {
  local e match="$1"
  shift
  for e; do [[ "$e" == "$match" ]] && return 0; done
  return 1
}

function nopluginlist {
  output "warn" "No plugin list found. Try running '${0##*/} index' to index everything."
}

function avail-plugins {
  if [ -f "${PLIST}" ]; then
    output "warn" "Available plugins:"
    mapfile -t plugins < "${PLIST}" || output "erro" "Failed to load plugin list."
    output "warn" "${plugins[@]}"
  else
    nopluginlist
  fi
}

function index {
  output "info" "Indexing plugins"
  truncate -s 0 "${PLIST}"
  for i in $(find "${DIR}"/plugins/* -type d | grep -P "(?<=\/plugins\/)([\w\d\-\_])*" -o); do
    echo "$i" >> "${PLIST}" && output "done" "Added plugin '$i'."
  done
  output "info" "Indexing extensions"
  truncate -s 0 "${ELIST}"
  for i in $(find "${DIR}"/extensions/* -type f | grep -P "(?<=\/extensions\/)([\w\d\-\_])*(\.func)" -o); do
    echo "$i" >> "${ELIST}" && output "done" "Added extension '$i'."
  done
}

function loadlists {
  mapfile -t plugins < "${PLIST}" || output "erro" "Failed to load plugin list."
  mapfile -t extensions < "${ELIST}" || output "erro" "Failed to load extension list."
  for i in "${extensions[@]}"; do
    source "${DIR}/extensions/$i" || output "warn" "Failed to import extension ${i}."
  done
}

function preparedirs {
  if mkdir "${DIR}"/plugins/ "${DIR}"/extensions/; then
    output "info" "Created a empty plugins and extensions directory."
  else
    output "err" "Could not create directory."
  fi
}

## Main run

[ ${DEV} = "true" ] && output "warn" "Running in development mode!"

if ! [ $# -eq 0 ] && ! [[ "$1" = "index" ]] && [ -f "${PLIST}" ] && [ -f "${ELIST}" ]; then
  loadlists
  main "$@"
elif [ -d "${DIR}"/plugins/ ] && [ -d "${DIR}"/extensions/ ]; then
  if [ $# -eq 0 ]; then
    output "warn" "Nothing to do!"
    avail-plugins
  elif [[ "$1" = "index" ]]; then
    index
  else
    nopluginlist
  fi
else
  preparedirs
fi
! [[ "$1" = "rawpl" ]] && output "done" "Made with ♥ by casKd | t.me/casKd_dev"
